# 9-region ISO3 -> region lookup for panel-member analyses.
# Lifted verbatim from
#   initial-exploration/explore-coder-level-data/07-calibration-by-coder-context.qmd  (region_map)
# — the project's curated scheme — so the re-identification diagnostic and the name-swap
# within-region pairing read one source. Frozen copy for reproducibility; if the source
# map changes, re-lift it.

# 186 countries, 9 regions.

region_map9 <- c(
  AUT = "The West",
  BEL = "The West",
  CAN = "The West",
  DNK = "The West",
  FIN = "The West",
  FRA = "The West",
  DEU = "The West",
  GRC = "The West",
  IRL = "The West",
  ISL = "The West",
  ITA = "The West",
  LUX = "The West",
  NLD = "The West",
  NOR = "The West",
  PRT = "The West",
  ESP = "The West",
  SWE = "The West",
  CHE = "The West",
  GBR = "The West",
  USA = "The West",
  AUS = "The West",
  NZL = "The West",
  CYP = "The West",
  MLT = "The West",
  ISR = "The West",
  ALB = "Eastern Europe",
  ARM = "Eastern Europe",
  BIH = "Eastern Europe",
  BGR = "Eastern Europe",
  HRV = "Eastern Europe",
  CZE = "Eastern Europe",
  EST = "Eastern Europe",
  GEO = "Eastern Europe",
  HUN = "Eastern Europe",
  LVA = "Eastern Europe",
  LTU = "Eastern Europe",
  MKD = "Eastern Europe",
  MDA = "Eastern Europe",
  MNE = "Eastern Europe",
  POL = "Eastern Europe",
  ROU = "Eastern Europe",
  SRB = "Eastern Europe",
  SVK = "Eastern Europe",
  SVN = "Eastern Europe",
  UKR = "Eastern Europe",
  XKX = "Eastern Europe",
  AZE = "C. Asia/Post-Sov.",
  BLR = "C. Asia/Post-Sov.",
  KAZ = "C. Asia/Post-Sov.",
  KGZ = "C. Asia/Post-Sov.",
  MNG = "C. Asia/Post-Sov.",
  RUS = "C. Asia/Post-Sov.",
  TJK = "C. Asia/Post-Sov.",
  TKM = "C. Asia/Post-Sov.",
  UZB = "C. Asia/Post-Sov.",
  ARG = "Latin America",
  BOL = "Latin America",
  BRA = "Latin America",
  CHL = "Latin America",
  COL = "Latin America",
  CRI = "Latin America",
  CUB = "Latin America",
  DOM = "Latin America",
  ECU = "Latin America",
  SLV = "Latin America",
  GTM = "Latin America",
  HTI = "Latin America",
  HND = "Latin America",
  JAM = "Latin America",
  MEX = "Latin America",
  NIC = "Latin America",
  PAN = "Latin America",
  PRY = "Latin America",
  PER = "Latin America",
  TTO = "Latin America",
  URY = "Latin America",
  VEN = "Latin America",
  GUY = "Latin America",
  SUR = "Latin America",
  BLZ = "Latin America",
  BHS = "Latin America",
  BRB = "Latin America",
  GRD = "Latin America",
  AFG = "S. Asia",
  BGD = "S. Asia",
  BTN = "S. Asia",
  IND = "S. Asia",
  MDV = "S. Asia",
  NPL = "S. Asia",
  PAK = "S. Asia",
  LKA = "S. Asia",
  BRN = "SE Asia",
  KHM = "SE Asia",
  TLS = "SE Asia",
  IDN = "SE Asia",
  LAO = "SE Asia",
  MYS = "SE Asia",
  MMR = "SE Asia",
  PHL = "SE Asia",
  SGP = "SE Asia",
  THA = "SE Asia",
  VDR = "SE Asia",
  VNM = "SE Asia",
  CHN = "E. Asia & Pacific",
  HKG = "E. Asia & Pacific",
  JPN = "E. Asia & Pacific",
  KOR = "E. Asia & Pacific",
  PRK = "E. Asia & Pacific",
  TWN = "E. Asia & Pacific",
  FJI = "E. Asia & Pacific",
  PNG = "E. Asia & Pacific",
  SLB = "E. Asia & Pacific",
  VUT = "E. Asia & Pacific",
  WSM = "E. Asia & Pacific",
  AGO = "Sub-Sah. Africa",
  BEN = "Sub-Sah. Africa",
  BWA = "Sub-Sah. Africa",
  BFA = "Sub-Sah. Africa",
  BDI = "Sub-Sah. Africa",
  CPV = "Sub-Sah. Africa",
  CMR = "Sub-Sah. Africa",
  CAF = "Sub-Sah. Africa",
  TCD = "Sub-Sah. Africa",
  COM = "Sub-Sah. Africa",
  COD = "Sub-Sah. Africa",
  COG = "Sub-Sah. Africa",
  CIV = "Sub-Sah. Africa",
  DJI = "Sub-Sah. Africa",
  GNQ = "Sub-Sah. Africa",
  ERI = "Sub-Sah. Africa",
  ETH = "Sub-Sah. Africa",
  GAB = "Sub-Sah. Africa",
  GMB = "Sub-Sah. Africa",
  GHA = "Sub-Sah. Africa",
  GIN = "Sub-Sah. Africa",
  GNB = "Sub-Sah. Africa",
  KEN = "Sub-Sah. Africa",
  LSO = "Sub-Sah. Africa",
  LBR = "Sub-Sah. Africa",
  MDG = "Sub-Sah. Africa",
  MWI = "Sub-Sah. Africa",
  MLI = "Sub-Sah. Africa",
  MRT = "Sub-Sah. Africa",
  MUS = "Sub-Sah. Africa",
  MOZ = "Sub-Sah. Africa",
  NAM = "Sub-Sah. Africa",
  NER = "Sub-Sah. Africa",
  NGA = "Sub-Sah. Africa",
  RWA = "Sub-Sah. Africa",
  STP = "Sub-Sah. Africa",
  SEN = "Sub-Sah. Africa",
  SLE = "Sub-Sah. Africa",
  SOM = "Sub-Sah. Africa",
  ZAF = "Sub-Sah. Africa",
  SSD = "Sub-Sah. Africa",
  SDN = "Sub-Sah. Africa",
  SWZ = "Sub-Sah. Africa",
  TZA = "Sub-Sah. Africa",
  TGO = "Sub-Sah. Africa",
  UGA = "Sub-Sah. Africa",
  ZMB = "Sub-Sah. Africa",
  ZWE = "Sub-Sah. Africa",
  DZA = "MENA",
  BHR = "MENA",
  EGY = "MENA",
  IRN = "MENA",
  IRQ = "MENA",
  JOR = "MENA",
  KWT = "MENA",
  LBN = "MENA",
  LBY = "MENA",
  MAR = "MENA",
  OMN = "MENA",
  PSE = "MENA",
  QAT = "MENA",
  SAU = "MENA",
  SYR = "MENA",
  TUN = "MENA",
  ARE = "MENA",
  YEM = "MENA",
  TUR = "MENA",
  SML = "Sub-Sah. Africa",
  SYC = "Sub-Sah. Africa",
  ZZB = "Sub-Sah. Africa",
  DDR = "Eastern Europe",
  YMD = "MENA"
)

region_order9 <- c(
  "The West",
  "Eastern Europe",
  "C. Asia/Post-Sov.",
  "Latin America",
  "S. Asia",
  "SE Asia",
  "E. Asia & Pacific",
  "Sub-Sah. Africa",
  "MENA"
)
